        messageString = (
            'INVITE sip:user@example.com SIP/2.0\r\n'
            'Max-Forwards: 80\r\n'
            'To: sip:j.user@example.com\r\n'
            'From: sip:caller@example.net;tag=93942939o2\r\n'
            'Contact: <sip:caller@hungry.example.net>\r\n'
            'Call-ID: clerr.0ha0isndaksdjweiafasdk3\r\n'
            'CSeq: 8 INVITE\r\n'
            'Via: SIP/2.0/UDP host5.example.com;branch=z9hG4bK-39234-23523\r\n'
            'Content-Type: application/sdp\r\n'
            'Content-Length: 9999\r\n'
            '\r\n'
            'v=0\r\n'
            'o=mhandley 29739 7272939 IN IP4 192.0.2.155\r\n'
            's=-\r\n'
            'c=IN IP4 192.0.2.155\r\n'
            't=0 0\r\n'
            'm=audio 49217 RTP/AVP 0 12\r\n'
            'm=video 3227 RTP/AVP 31\r\n'
            'a=rtpmap:31 LPC\r\n'
        )
