        messageString = (
            'INVITE sip:user@example.com?Route=%3Csip:example.com%3E SIP/2.0\r\n'
            'To: sip:user@example.com\r\n'
            'From: sip:caller@example.net;tag=341518\r\n'
            'Max-Forwards: 7\r\n'
            'Contact: <sip:caller@host39923.example.net>\r\n'
            'Call-ID: escruri.23940-asdfhj-aje3br-234q098w-fawerh2q-h4n5\r\n'
            'CSeq: 149209342 INVITE\r\n'
            'Via: SIP/2.0/UDP host-of-the-hour.example.com;branch=z9hG4bKkdjuw\r\n'
            'Content-Type: application/sdp\r\n'
            'Content-Length: 150\r\n'
            '\r\n'
            'v=0\r\n'
            'o=mhandley 29739 7272939 IN IP4 192.0.2.1\r\n'
            's=-\r\n'
            'c=IN IP4 192.0.2.1\r\n'
            't=0 0\r\n'
            'm=audio 49217 RTP/AVP 0 12\r\n'
            'm=video 3227 RTP/AVP 31\r\n'
            'a=rtpmap:31 LPC\r\n'
        )
