        messageString = (
            'INVITE sip:user@example.com SIP/2.0\r\n'
            'Contact: <sip:caller@host5.example.net>\r\n'
            'To: sip:j.user@example.com\r\n'
            'From: sip:caller@example.net;tag=8392034\r\n'
            'Max-Forwards: 70\r\n'
            'Call-ID: invut.0ha0isndaksdjadsfij34n23d\r\n'
            'CSeq: 235448 INVITE\r\n'
            'Via: SIP/2.0/UDP somehost.example.com;branch=z9hG4bKkdjuw\r\n'
            'Content-Type: application/unknownformat\r\n'
            'Content-Length: 40\r\n'
            '\r\n'
            '<audio>\r\n'
            ' <pcmu port="443"/>\r\n'
            '</audio>\r\n'
        )
