        messageString = (
            'INVITE sip:user@example.com SIP/2.0\r\n'
            'To: "I have a user name of extremeextremeextremeextremeextremeextremeextremeextremeextremeextreme proportion"<sip:user@example.com:6000;unknownparam1=verylonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglongvalue;longparamnamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamename=shortvalue;verylonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglongParameterNameWithNoValue>\r\n'
            'F: sip:amazinglylongcallernameamazinglylongcallernameamazinglylongcallernameamazinglylongcallernameamazinglylongcallername@example.net;tag=12982982982982982982982982982982982982982982982982982982982982982982982982982982982982982982982982982982982982982982982982982982982982982982982982982982424;unknownheaderparamnamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamenamename=unknowheaderparamvaluevaluevaluevaluevaluevaluevaluevaluevaluevaluevaluevaluevaluevaluevalue;unknownValuelessparamnameparamnameparamnameparamnameparamnameparamnameparamnameparamnameparamnameparamname\r\n'
            'Call-ID: longreq.onereallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallyreallylongcallid\r\n'
            'CSeq: 3882340 INVITE\r\n'
            'Unknown-LongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLongLong-Name: unknown-longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong-value; unknown-longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong-parameter-name = unknown-longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong-parameter-value\r\n'
            'Via: SIP/2.0/TCP sip33.example.com\r\n'
            'v: SIP/2.0/TCP sip32.example.com\r\n'
            'V: SIP/2.0/TCP sip31.example.com\r\n'
            'Via: SIP/2.0/TCP sip30.example.com\r\n'
            'ViA: SIP/2.0/TCP sip29.example.com\r\n'
            'VIa: SIP/2.0/TCP sip28.example.com\r\n'
            'VIA: SIP/2.0/TCP sip27.example.com\r\n'
            'via: SIP/2.0/TCP sip26.example.com\r\n'
            'viA: SIP/2.0/TCP sip25.example.com\r\n'
            'vIa: SIP/2.0/TCP sip24.example.com\r\n'
            'vIA: SIP/2.0/TCP sip23.example.com\r\n'
            'V :  SIP/2.0/TCP sip22.example.com\r\n'
            'v :  SIP/2.0/TCP sip21.example.com\r\n'
            'V  : SIP/2.0/TCP sip20.example.com\r\n'
            'v  : SIP/2.0/TCP sip19.example.com\r\n'
            'Via : SIP/2.0/TCP sip18.example.com\r\n'
            'Via  : SIP/2.0/TCP sip17.example.com\r\n'
            'Via: SIP/2.0/TCP sip16.example.com\r\n'
            'Via: SIP/2.0/TCP sip15.example.com\r\n'
            'Via: SIP/2.0/TCP sip14.example.com\r\n'
            'Via: SIP/2.0/TCP sip13.example.com\r\n'
            'Via: SIP/2.0/TCP sip12.example.com\r\n'
            'Via: SIP/2.0/TCP sip11.example.com\r\n'
            'Via: SIP/2.0/TCP sip10.example.com\r\n'
            'Via: SIP/2.0/TCP sip9.example.com\r\n'
            'Via: SIP/2.0/TCP sip8.example.com\r\n'
            'Via: SIP/2.0/TCP sip7.example.com\r\n'
            'Via: SIP/2.0/TCP sip6.example.com\r\n'
            'Via: SIP/2.0/TCP sip5.example.com\r\n'
            'Via: SIP/2.0/TCP sip4.example.com\r\n'
            'Via: SIP/2.0/TCP sip3.example.com\r\n'
            'Via: SIP/2.0/TCP sip2.example.com\r\n'
            'Via: SIP/2.0/TCP sip1.example.com\r\n'
            'Via: SIP/2.0/TCP host.example.com;received=192.0.2.5;branch=verylonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglongbranchvalue\r\n'
            'Max-Forwards: 70\r\n'
            'Contact: <sip:amazinglylongcallernameamazinglylongcallernameamazinglylongcallernameamazinglylongcallernameamazinglylongcallername@host5.example.net>\r\n'
            'Content-Type: application/sdp\r\n'
            'l: 150\r\n'
            '\r\n'
            'v=0\r\n'
            'o=mhandley 29739 7272939 IN IP4 192.0.2.1\r\n'
            's=-\r\n'
            'c=IN IP4 192.0.2.1\r\n'
            't=0 0\r\n'
            'm=audio 49217 RTP/AVP 0 12\r\n'
            'm=video 3227 RTP/AVP 31\r\n'
            'a=rtpmap:31 LPC\r\n'
        )
