        messageString = (
            'INVITE  sip:user@example.com  SIP/2.0\r\n'
            'Max-Forwards: 8\r\n'
            'To: sip:user@example.com\r\n'
            'From: sip:caller@example.net;tag=8814\r\n'
            'Call-ID: lwsstart.dfknq234oi243099adsdfnawe3@example.com\r\n'
            'CSeq: 1893884 INVITE\r\n'
            'Via: SIP/2.0/UDP host1.example.com;branch=z9hG4bKkdjuw3923\r\n'
            'Contact: <sip:caller@host1.example.net>\r\n'
            'Content-Type: application/sdp\r\n'
            'Content-Length: 150\r\n'
            '\r\n'
            'v=0\r\n'
            'o=mhandley 29739 7272939 IN IP4 192.0.2.1\r\n'
            's=-\r\n'
            'c=IN IP4 192.0.2.1\r\n'
            't=0 0\r\n'
            'm=audio 49217 RTP/AVP 0 12\r\n'
            'm=video 3227 RTP/AVP 31\r\n'
            'a=rtpmap:31 LPC\r\n'
        )
