        messageString = (
            'INVITE sip:user@example.com SIP/2.0\r\n'
            'To: "Mr. J. User <sip:j.user@example.com>\r\n'
            'From: sip:caller@example.net;tag=93334\r\n'
            'Max-Forwards: 10\r\n'
            'Call-ID: quotbal.aksdj\r\n'
            'Contact: <sip:caller@host59.example.net>\r\n'
            'CSeq: 8 INVITE\r\n'
            'Via: SIP/2.0/UDP 192.0.2.59:5050;branch=z9hG4bKkdjuw39234\r\n'
            'Content-Type: application/sdp\r\n'
            'Content-Length: 152\r\n'
            '\r\n'
            'v=0\r\n'
            'o=mhandley 29739 7272939 IN IP4 192.0.2.15\r\n'
            's=-\r\n'
            'c=IN IP4 192.0.2.15\r\n'
            't=0 0\r\n'
            'm=audio 49217 RTP/AVP 0 12\r\n'
            'm=video 3227 RTP/AVP 31\r\n'
            'a=rtpmap:31 LPC\r\n'
        )
