        messageString = (
            'INVITE sip:user@example.com SIP/2.0\r\n'
            'To: sip:j_user@example.com\r\n'
            'Contact: <sip:caller@host15.example.net>\r\n'
            'From: sip:caller@example.net;tag=234\r\n'
            'Max-Forwards: 5\r\n'
            'Call-ID: sdp01.ndaksdj9342dasdd\r\n'
            'Accept: text/nobodyKnowsThis\r\n'
            'CSeq: 8 INVITE\r\n'
            'Via: SIP/2.0/UDP 192.0.2.15;branch=z9hG4bKkdjuw\r\n'
            'Content-Length: 150\r\n'
            'Content-Type: application/sdp\r\n'
            '\r\n'
            'v=0\r\n'
            'o=mhandley 29739 7272939 IN IP4 192.0.2.5\r\n'
            's=-\r\n'
            'c=IN IP4 192.0.2.5\r\n'
            't=0 0\r\n'
            'm=audio 49217 RTP/AVP 0 12\r\n'
            'm=video 3227 RTP/AVP 31\r\n'
            'a=rtpmap:31 LPC\r\n'
        )
