        messageString = (
            'INVITE sip:alan@jasomi.com\r\n'
            'TO : alan@jasomi.com\r\n'
            'From: ralph@example.com\r\n'
            'MaX-fOrWaRdS: 0068\r\n'
            'Call-ID: test.0ha0isndaksdj@192.0.2.1\r\n'
            'Xyzzy-2: this is the number ten : 10\r\n'
            'Xyzzy-3: INVITE\r\n'
            'Xyzzy: 10000000000\r\n'
            'Meaning: foo bar spam\r\n'
            'Foobar roobar\r\n'
            'Content-Length: 18\r\n'
            'Content-Type: application/sdp\r\n'
            '\r\n'
            'v=0\r\n'
            'testing=123\r\n'
        )
